In [1]:
import numpy as np

In [3]:
import tensorflow as tf

In [21]:
observations = 1000
xs = np.random.uniform(low = -10,high = 10,size = (observations,1))
zs = np.random.uniform(-10,10,(observations,1))

generated_inputs = np.column_stack((xs,zs))
                                                                      
noise = np.random.uniform(-1,1,(observations,1))

generated_targets = 2*xs - 5*zs + 5 + noise

np.savez("tf_intro", inputs = generated_inputs, targets = generated_targets)

In [22]:
traning_data = np.load("tf_intro.npz")


In [29]:
input_size = 2
output_size = 1

model = tf.keras.Sequential([
    tf.keras.layers.Dense(output_size)
])

model.compile(optimizer = 'sgd', loss = 'mean_squared_error')

model.fit(traning_data['inputs'],traning_data['targets'], epochs = 100, verbose = 2)


Epoch 1/100
32/32 - 0s - loss: 59.6434
Epoch 2/100
32/32 - 0s - loss: 4.5945
Epoch 3/100
32/32 - 0s - loss: 1.5129
Epoch 4/100
32/32 - 0s - loss: 0.6555
Epoch 5/100
32/32 - 0s - loss: 0.4287
Epoch 6/100
32/32 - 0s - loss: 0.3624
Epoch 7/100
32/32 - 0s - loss: 0.3480
Epoch 8/100
32/32 - 0s - loss: 0.3351
Epoch 9/100
32/32 - 0s - loss: 0.3343
Epoch 10/100
32/32 - 0s - loss: 0.3396
Epoch 11/100
32/32 - 0s - loss: 0.3348
Epoch 12/100
32/32 - 0s - loss: 0.3329
Epoch 13/100
32/32 - 0s - loss: 0.3379
Epoch 14/100
32/32 - 0s - loss: 0.3387
Epoch 15/100
32/32 - 0s - loss: 0.3384
Epoch 16/100
32/32 - 0s - loss: 0.3388
Epoch 17/100
32/32 - 0s - loss: 0.3341
Epoch 18/100
32/32 - 0s - loss: 0.3376
Epoch 19/100
32/32 - 0s - loss: 0.3354
Epoch 20/100
32/32 - 0s - loss: 0.3410
Epoch 21/100
32/32 - 0s - loss: 0.3338
Epoch 22/100
32/32 - 0s - loss: 0.3334
Epoch 23/100
32/32 - 0s - loss: 0.3409
Epoch 24/100
32/32 - 0s - loss: 0.3387
Epoch 25/100
32/32 - 0s - loss: 0.3378
Epoch 26/100
32/32 - 0s - loss: 0

In [32]:
model.layers[0].get_weights()


[array([[ 2.010238 ],
        [-5.0056486]], dtype=float32),
 array([4.978362], dtype=float32)]

In [33]:
weights = model.layers[0].get_weights()[0]
weights

array([[ 2.010238 ],
       [-5.0056486]], dtype=float32)

In [34]:
model.predict_on_batch(traning_data['inputs'])

array([[-36.716362  ],
       [ 23.956665  ],
       [ 26.235153  ],
       [-42.706547  ],
       [-38.309093  ],
       [-32.550808  ],
       [ -1.7053757 ],
       [ 27.719467  ],
       [  6.1368475 ],
       [ 12.934429  ],
       [ 69.60292   ],
       [ 13.354879  ],
       [-47.04362   ],
       [ 63.68512   ],
       [ 24.585377  ],
       [ 44.700523  ],
       [ -8.565063  ],
       [-16.644695  ],
       [ 44.57293   ],
       [ 13.3521595 ],
       [ 37.87153   ],
       [  6.825043  ],
       [-46.14543   ],
       [ 22.71923   ],
       [-21.9221    ],
       [ 11.754939  ],
       [-15.061744  ],
       [-18.100567  ],
       [ -5.8964767 ],
       [-40.1103    ],
       [ 18.503681  ],
       [-13.95575   ],
       [ 33.97736   ],
       [-24.779877  ],
       [-45.76879   ],
       [ 11.96147   ],
       [ 10.696796  ],
       [  0.1277113 ],
       [ 21.412144  ],
       [ 11.463622  ],
       [ -0.09877491],
       [  6.6933994 ],
       [ 17.497711  ],
       [ 13